# Python 람다 함수를 위한 Dockerfile
FROM python:3.10.11

# Poetry 설치
RUN pip install -U poetry

# 경로 정의
WORKDIR /workdir

# 로컬에 있는 pyproject.toml, poetry.lock 파일을 컨테이너로 복사
COPY poetry.lock pyproject.toml /workdir/

# Poetry를 이용하여 의존성 설치
RUN poetry config virtualenvs.create false \
 && poetry install --no-root --no-interaction

# 로컬에 있는 소스코드를 컨테이너로 복사
COPY . /workdir

# 애플리케이션 실행
CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]