[tool.poetry]
name = "speech-api"
version = "0.1.0"
description = ""
authors = ["gksdyd <gksdyd009@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
fastapi = "^0.115.13"
uvicorn = "^0.34.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
